service: my-store-app-backend

frameworkVersion: "3"

plugins:
  - serverless-auto-swagger
  - serverless-offline
  - serverless-webpack

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: Delfin_admin
  environment:
    DB_USER: ${env:DB_USER}
    DB_SERVER: ${env:DB_SERVER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}
  httpApi:
    cors: true

configValidationMode: error

functions:
  getProductsList:
    handler: productService/getProductsList.handler
    events:
      - httpApi:
          path: /products
          method: get
          swaggerTags: ['Products']
  getProductById:
    handler: productService/getProductById.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: get
          swaggerTags: ['Products']
  createProduct:
    handler: productService/createProduct.handler
    events:
      - httpApi:
          path: /products
          method: post
          swaggerTags: ['Products']

custom:
  autoswagger:
    title: 'product-service'
    useStage: true
    basePath: '/dev'
    typefiles: ['./productService/models.ts']
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'
    excludeFiles: '__tests__/**/*.test.ts'