service: my-store-app-backend

frameworkVersion: "3"

plugins:
  - serverless-auto-swagger
  - serverless-offline
  - serverless-webpack

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: ${env:AWS_PROFILE}
  environment:
    DB_USER: ${env:DB_USER}
    DB_SERVER: ${env:DB_SERVER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}
    AWS_UPLOAD_BUCKET: ${env:AWS_UPLOAD_BUCKET}
    AWS_UPLOAD_BUCKET_CATALOG: ${env:AWS_UPLOAD_BUCKET_CATALOG}
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 's3:ListBucket'
      Resource:
        - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - ${env:AWS_UPLOAD_BUCKET}

configValidationMode: error

functions:
  getProductsList:
    handler: productService/getProductsList.handler
    events:
      - httpApi:
          path: /products
          method: get
          swaggerTags: ['Products']
  getProductById:
    handler: productService/getProductById.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: get
          swaggerTags: ['Products']
  createProduct:
    handler: productService/createProduct.handler
    events:
      - httpApi:
          path: /products
          method: post
          swaggerTags: ['Products']
  importProductsFile:
    handler: importService/importProductsFile.handler
    events:
      - httpApi:
          path: /import
          method: GET
  importFileParser:
    handler: importService/importFileParser.handler
    events:
      - s3:
          bucket: ${env:AWS_UPLOAD_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${env:AWS_UPLOAD_BUCKET_CATALOG}/
            - suffix: .csv
          existing: true

custom:
  autoswagger:
    title: 'product-service'
    useStage: true
    basePath: '/dev'
    typefiles: ['./productService/models.ts']
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'
    excludeFiles: '__tests__/**/*.test.ts'