service: my-store-app-backend

frameworkVersion: "3"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: Delfin_admin
  httpApi:
    cors: true

functions:
  getProductsList:
    handler: productService/getProductsList.handler
    events:
      - httpApi:
          path: /products
          method: get
  getProductById:
    handler: productService/getProductById.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: get

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'
    excludeFiles: '__tests__/**/*.test.ts'