service: my-store-app-backend

frameworkVersion: "3"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: Delfin_admin
  httpApi:
    cors: true

functions:
  getProductsList:
    handler: lambdas/getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductById:
    handler: lambdas/getProductById.getProductById
    events:
      - httpApi:
          path: /products/{productId}
          method: get